backend:
  name: git-gateway
  repo: lara/laradecoco.dev
  branch: master

site_url: "https://laradecoco.dev"
media_folder: "src/photography/images"
public_folder: "/photography/images"

collections:
  - name: "blog"
    label: "Post"
    folder: "src/blog"
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Post Tags"
        name: "postTags"
        widget: "list"
      - label: "Date"
        name: "date"
        widget: "datetime"
  - name: "photography"
    label: "Photo"
    folder: "src/photography"
    slug: "{{slug}}"
    preview_path: "photography/{{slug}}"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
