backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
site_url: "https://example.com"
media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Posts"
    folder: "src/blog/posts"
    slug: "{{slug}}"
    preview_path: "blog/posts/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
