backend:
  name: git-gateway
  repo: lara/dilaraaydin.com
  branch: master

publish_mode: editorial_workflow
site_url: "https://dilaraaydin.com"
media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Posts"
    folder: "src/blog"
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Post Tags"
        name: "postTags"
        widget: "list"
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
